# See: https://dart.dev/tools/pub/pubspec
name: model_viewer
version: 0.0.0
description: >-
  A Flutter widget for rendering interactive 3D models in the glTF and GLB
  formats.
homepage: https://github.com/drydart/model_viewer.dart
repository: https://github.com/drydart/model_viewer.dart
issue_tracker: https://github.com/drydart/model_viewer.dart/issues
documentation:
dependencies:
  meta: ^1.1.8
dev_dependencies:
  test: any
dependency_overrides:
environment:
  sdk: '>=2.8.1 <3.0.0'
executables:
